services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    ports:
      - "3000:3000"
    command: npm start
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', r => process.exit(r.statusCode===200?0:1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  default:
    name: life-timer_prod
