services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      GOOGLE_CSE_ID: ${GOOGLE_CSE_ID}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "3000:3000"
    command: npm start
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  default:
    name: life-timer_prod
