services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
      # Provide your secrets via an .env file or your orchestrator
      GOOGLE_CSE_ID: ${GOOGLE_CSE_ID}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    # Development mounts: keep container node_modules separate to avoid host override
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
