services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
    # No server secrets required for Wikipedia API
    # Development mounts: keep container node_modules and .next inside container
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
